# Generated by Django 4.0.2 on 2022-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0003_profile_forget_pwd_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedIn',
            field=models.URLField(max_length=100),
        ),
    ]
